### ISSUE TITLE
SCCM as a AutomatedLab custom role 

### ISSUE THREAD

**Issue by raandree** [GlennJC/AL-Scripts#10]
Would you be interested in integrating the SCCM stuff directly into AL? There is the feature of custom roles and your SCCM code seems to be the ideal candidate.

There is no documentation about this yet, but I am happy to assist.

**Comment by GlennJC** [comment]
@raandree absolutely, sounds like a great idea.  

I was hoping to get these available as Custom roles eventually, just wasn't 100% sure about the requirements without reverse engineering the process expected from the main scripts.

**Comment by GlennJC** [comment]
Initial Version completed and tested.

**Comment by raandree** [comment]
Thanks, I will test the role and add it to AL. This might be quite nice for a bunch of people.
