### ISSUE TITLE
PSDefaultParameterValues must be defined after calling New-LabDefinition

### ISSUE THREAD

**Issue by raandree** [GlennJC/AL-Scripts#8]
In SCCM Server Build.ps1 the PSDefaultParameterValues hashtable is created before calling New-LabDefinition. New-LabDefinition removes all elements from PSDefaultParameterValues related to AutomatedLab (see https://github.com/AutomatedLab/AutomatedLab/blob/0e707451d6821e382c50c9bd87d978d902749b10/AutomatedLabDefinition/AutomatedLabDefinition.psm1#L593)

**Comment by GlennJC** [comment]
Fixed, thanks 👍
