### ISSUE TITLE
SCCM Installation and ISO file usage

### ISSUE THREAD

**Issue by raandree** [GlennJC/AL-Scripts#9]
Wouldn't it be easier to mount the ISO and install SCCM form there directly? Or is there a reason why you copy the files?

**Comment by GlennJC** [comment]
Hey @raandree . Only was doing it this way as the trial download available from the TechNet Evaluation Center is a self extracting EXE, not an ISO file. Would much rather do it the ISO way to be sure, but don't have access to the media to test.

**Comment by raandree** [comment]
It is fine to stay with the extracting exe.
